Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", path: "bootstrap.sh"	
  config.vm.provision "shell", path: "install_mongo.sh"
  config.vm.provision "shell", path: "load_mongo_schema.sh"
end


